@startuml

class Adherent {
    - {static} string numeroAdhesion
    - string prenom
    - string nom
    - string email
    - DateTime dateAdhesion
    - genererNumero() : void
    + renouvelerAdhesion() : void
    + afficher() : string
    + isAdhesionValable() : bool
}



class Emprunt {
    - DateTime dateEmprunt
    - DateTime dateRetourEstimee
    - ?DateTime dateRetour
    - Adherent adherent
    - Media media
    + afficher() : string
    + isEnCours() : bool
    + isEnAlerte() : bool
    + isDureeDepassee() : bool
}




abstract class Media {
    # string titre
    # int dureeEmprunt
    + {abstract} afficher() : string
}

class Livre extends Media {
    - string auteur
    - int nbPages
    + afficher() : string
}

class Blu-Ray extends Media {
    - string realisateur
    - string duree
    - string anneeSortie
    + afficher() : string
}

class Magazine extends Media {
    - {static} string numero
    - string datePublication
    + afficher() : string
}


Adherent "1.*" --> "0.*" Media
(Adherent, Media) .. Emprunt

@enduml